class FailedGetDataException(Exception):
    pass

class AuthException(Exception):
    pass
